- name: "HTH | PyCharm | Validate input variables"
  ansible.utils.validate:
    data: "{{ pycharm }}"
    criteria: "{{ lookup('file',  'assertions/criteria/pycharm-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
    - pycharm is defined

- name: "HTH | PyCharm | Manage clients"
  ansible.builtin.include_tasks: clients/main.yml
  loop: "{{ pycharm.clients }}"
  loop_control:
    loop_var: client
