- name: "HTH | PyCharm | Set client archive name"
  ansible.builtin.set_fact:
    hth_pycharm_client_archive_name: "pycharm-{{ client.version }}.tar.gz"

- name: "HTH | PyCharm | Set client archive download path"
  ansible.builtin.set_fact:
    hth_pycharm_client_archive_path: "{{ hth_pycharm_default_download_path }}{{ hth_pycharm_client_archive_name }}"

- block:

  - name: "HTH | PyCharm | Check for downloaded client archive"
    ansible.builtin.stat:
      path: "{{ hth_pycharm_client_archive_path }}"
    register: hth_pycharm_client_archive_stat

  - name: "HTH | PyCharm | Download client archive"
    ansible.builtin.get_url:
      url: "{{ hth_pycharm_default_host }}{{ hth_pycharm_default_url_path }}{{ hth_pycharm_client_archive_name }}"
      dest: "{{ hth_pycharm_client_archive_path }}"
      checksum: "sha256: {{ client.checksum }}"
    register: hth_pycharm_client_archive_download_state
    when:
      - not hth_pycharm_client_archive_stat.stat.exists

  - name: "HTH | PyCharm | Create client install directory"
    ansible.builtin.file:
      path: "{{ hth_pycharm_client_installation_path }}"
      owner: "{{ pycharm.location.owner | default('root') }}"
      group: "{{ pycharm.location.group | default('root') }}"
      mode: "{{ pycharm.location.mode | default('0755') }}"
      state: directory
      modification_time: preserve
      access_time: preserve
      recurse: yes
    when:
      - not hth_pycharm_client_version_dir_state.stat.exists

  - name: "HTH | PyCharm | Extract client archive"
    ansible.builtin.unarchive:
      remote_src: yes
      src: "{{ hth_pycharm_client_archive_path }}"
      dest: "{{ hth_pycharm_client_installation_path }}"
      owner: "{{ pycharm.location.owner | default('root') }}"
      group: "{{ pycharm.location.group | default('root') }}"
      extra_opts: [--strip-components=1]
    register: hth_pycharm_client_unarchive_state

  - name: "HTH | PyCharm | Add write permissions for custom owner group"
    file:
      path: "{{ hth_pycharm_client_installation_path }}"
      mode: "ug+w"
      recurse: yes
    when:
      - pycharm.location is defined
      - pycharm.location.group is defined
      - pycharm.location.group != 'root'

  always:

    - name: "HTH | PyCharm | Cleanup downloaded client archive"
      ansible.builtin.file:
        path: "{{ hth_pycharm_client_archive_path }}"
        state: absent
      when:
        - hth_pycharm_default_cleanup_on_install
